//
//  FirstViewController.swift
//  LytPlayer
//
//  Created by Bo Frese on 5/2-16.
//  Copyright © 2016 nota.dk. All rights reserved.
//

import UIKit
import AudioToolbox
import AVFoundation
import WebKit


class FirstViewController: UIViewController, WKNavigationDelegate {

    @IBOutlet weak var webViewPlaceholder: UIView!
    var webView: WKWebView?
    let player = Player()
    @IBOutlet weak var playPauseButton: UIButton!
    
    @IBAction func playButtonPressed(sender: UIButton) {
        
        if ( player.isPlaying ) {
            player.pause()
        } else {
            player.play()
        }
        
        updatePlayButton()
    }
    
    func updatePlayButton() {
        let buttonTitle = ( player.isPlaying ? "Pause" : "Play")
        playPauseButton.setTitle(buttonTitle, forState: .Normal)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        updatePlayButton()
    }
    
    override func viewWillAppear(animated: Bool) {
        
        let prefs = WKPreferences()
        let conf = WKWebViewConfiguration()
        prefs.javaScriptCanOpenWindowsAutomatically = true
        prefs.javaScriptEnabled = true
        conf.preferences = prefs
        
        self.webView = WKWebView(frame: self.webViewPlaceholder.bounds, configuration: conf) // instantiate WKWebView
        self.webView?.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
        self.webView?.allowsBackForwardNavigationGestures = true
        self.webViewPlaceholder.addSubview(self.webView!)
        
        
        if let path = NSBundle.mainBundle().pathForResource( "18716/18716" , ofType: "htm") {
            let url  = NSURL.fileURLWithPath(path)
            let request = NSURLRequest(URL: url)
            webView?.loadRequest(request)
            webView?.navigationDelegate = self
            webView?.allowsBackForwardNavigationGestures = true
        }

        
            /*
        if let startUrl = NSURL(string:"http://m.e17.dk/") {
            let request = NSURLRequest(URL: startUrl)
            webView?.loadRequest(request)
            webView?.navigationDelegate = self
            webView?.allowsBackForwardNavigationGestures = true
        }
*/
        
        super.viewWillAppear(animated)
    }
    
    // ............ WKNavigationDelegate ................
    
    // Start the network activity indicator when the web view is loading
    func webView(webView: WKWebView,didStartProvisionalNavigation navigation: WKNavigation){
        UIApplication.sharedApplication().networkActivityIndicatorVisible = true
    }
    
    // Stop the network activity indicator when the loading finishes
    func webView(webView: WKWebView,didFinishNavigation navigation: WKNavigation){
        UIApplication.sharedApplication().networkActivityIndicatorVisible = false
    }

    // Policy when clicking the link
    func webView(webView: WKWebView, decidePolicyForNavigationAction navigationAction: WKNavigationAction, decisionHandler: (WKNavigationActionPolicy) -> Void) {
        NSLog("webView decidePolicyForNavigationAction... ")
        NSLog( navigationAction.description)
        if let url = navigationAction.request.URL,
            let ext = url.pathExtension
        {
            if ( ext == "smil") {
                decisionHandler(.Cancel)
                var html = "<html><body><H1>TODO</H1>"
                if let smilFile = url.pathComponents?.last {
                    html += smilFile
                }
                html += "</body></html>"
                webView.loadHTMLString(html, baseURL: nil)
            } else {
                decisionHandler(.Allow)
            }
        } else {
            decisionHandler(.Allow)
        }
    }
    
    // Policy after we got the response
    func webView(webView: WKWebView,
        decidePolicyForNavigationResponse navigationResponse: WKNavigationResponse,decisionHandler: ((WKNavigationResponsePolicy) -> Void)){
            NSLog("webView decidePolicyForNavigationResponse....")
            NSLog(navigationResponse.response.description)
            decisionHandler(.Allow)
    }
    
    ///////////// Autogenerated Boilerplate code ........////////////////////////

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

